version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: my_store
      MYSQL_USER: cfcode92
      MYSQL_ROOT_PASSWORD: cfcode92
      MY_SQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: cfcode92
      MYSQL_USER: cfcode92
      MYSQL_PORT: 3306
      PMA_HOST: mysql
    ports:
      - 8080:80
